### ISSUE TITLE
Remove pre-req for sql-crud

### ISSUE THREAD

**Issue by RDegnen** [ga-wdi-boston/rails-activerecord-crud-study#13]
We gave this study the night before we taught sql-crud. Some students were confused and reading through the sql-crud class

**Comment by laurenfazah** [comment]
This is delivered after sql-crud and rails-api for 013, so not sure it's an applicable issue moving forward.

**Comment by gaand** [comment]
I think we want to keep the prerequisite.

**Comment by jrhorn424** [comment]
> I think we want to keep the prerequisite.

I agree.

**Comment by gaand** [comment]
@RDegnen, @laurenfazah, @jrhorn424 This thread leads me to close.
